name: ci

on:
  workflow_dispatch:
  push:
    tags:
    - '*'
  
  pull_request:

jobs:
  build_policy:
    runs-on: ubuntu-latest
    name: build

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Read config
      id: config
      uses: opcr-io/ga-yaml-parser@v0.1
      with:
        file: .github/config-policy.yaml

    - name: Policy Build
      id: policy-build
      uses: opcr-io/policy-build-action@v2
      with:
        src: content/src
        tag: ${{ steps.config.outputs.repo }}
        revision: "$GITHUB_SHA"
      env:
        POLICY_DEFAULT_DOMAIN: ${{ steps.config.outputs.server }}
